my_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # index
    path('<int:pk>/', views.DetailView.as_view(), name='detail'), # detail
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('about/', views.about, name='about')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/models.py
import datetime 
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean = True,
        ordering = 'pub_date',
        description = 'Published Recently?'
    )

    def was_published_recently(self):
        yesterday = timezone.now() - datetime.timedelta(days=1)
        return yesterday <= self.pub_date <= timezone.now()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.urls import reverse
from django.db.models import F, FilteredRelation, Q
from django.views import generic
from django.utils import timezone
from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # Returns the last 5 posted polls
        questions = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
        questions = [question for question in questions if question.choice_set.count() > 1][:5]
        return questions


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        questions = Question.objects.filter(pub_date__lte=timezone.now())
        return questions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['question'].choice_set.count() >= 2:
            return context

class ResultsView(generic.DetailView):
    template_name = 'polls/results.html'
    model = Question

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get_context_data(self, **args):
        context = super().get_context_data(**args)
        if context['question'].choice_set.count() >= 2:
            choices = context['question'].choice_set.all()
            context['total'] = sum(choice.votes for choice in choices)
            context['choices'] = choices
            return context
        else:
            return []



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You did not select a choice'
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def about(request):
    return render(request, 'polls/about.html')

polls/templates/polls/about.html
{% extends 'polls/base.html' %}
{% load static %}

{% block title %} About | {% endblock %}

{% block content %}

    <div class="mx-auto p-6 w-full">
        <h1 class="underline text-2xl font-semibold mb-2">About</h1>
        <p>Pollz is a Django web application that allows users to vote in polls.</p>
        <p>Github Repository for Pollz Web App:
            <a class="text-yellow-600 underline hover:text-primary" href="https://github.com/tomjames156/polling_app" target="_blank" rel="norefferer">Polling App</a>
        </p>
        <p>Created by Tomisin Akinwande. Tutorial from the <a class="text-yellow-600 underline hover:text-primary" href="Django Documentation" rel="norefferer" target="_blank">Django Documentation</a></p>
        <p class="mt-4 mb-2 text-xl font-semibold">Contact Me:</p>
        <div class="grid grid-cols-2 min-w-1/2">
            <a href="https://twitter.com/tomisnakinwande" rel="norefferer" target="_blank"><i class="fa-brands fa-twitter p-1 text-primary bg-black rounded-full"></i> Twitter <br><span class="text-yellow-600 text-sm hover:text-primary">@tomisnakinwande</span></a>
            <a href="https://github.com/tomjames156" rel="norefferer" target="_blank"><i class="fa-brands fa-github p-1 text-primary bg-black rounded-full"></i> Github <br><span class="text-yellow-600 text-sm hover:text-primary">tomjames156</span></a>
        </div>
        {% comment %} <img src="{% static 'polls/images/wizzy.png' %}" alt="Wizzy-wizz"> {% endcomment %}
    </div>

{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en" data-theme="bumblebee">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.50.0/dist/full.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.tailwindcss.com"></script>
    <style>a br{
      display: none;
      }
      
      @media screen and (max-width: 430px) {
          a br{
              display: block;
          }
      } 
    </style>
    <title>{% block title %}{% endblock %}Pollz</title>
</head>
<body>
    <!-- Header/Navbar  -->
    <div class="navbar bg-base-100">
        <div class="navbar-start">
          <div class="dropdown">
            <label tabindex="0" class="btn btn-ghost btn-circle">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
            </label>
            <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
              <li><a href={% url 'polls:index' %}>Recent Polls</a></li>
              <li><a href={% url 'polls:about' %}>About</a></li>
            </ul>
          </div>
        </div>
        <div class="navbar-center">
          <a href={% url 'polls:index' %} class="btn font-bold btn-ghost normal-case text-3xl">Pollz</a>
        </div>
        <div class="navbar-end">
          <button class="btn btn-ghost btn-circle hover:cursor-default hover:bg-transparent text-transparent">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
          </button>
          <button class="btn btn-ghost btn-circle hover:cursor-default text-transparent hover:bg-transparent">
            <div class="indicator">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
            </div>
          </button>
        </div>
      </div>
      
      {% block content %}
      {% endblock %}
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="w-full p-6">
    {% if question.choice_set.all %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend class="text-xl font-bold mb-2">{{ question.question_text }}</legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter}} ">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input class="btn btn-secondary mt-4" type="submit" value="Vote">
    </form>
    {%else %}
        <p class="font-semibold">Question Does Not Exist</p>
        <a class='btn btn-secondary mt-4' href="{% url 'polls:index' %}">Back to Home</a>
    {% endif %}
</div> 
{% endblock %}

<!-- <select class="select select-accent w-full max-w-xs">
        <option disabled selected>Question: {{ question.question_text }}</option>        
            {% for choice in choices %}
                <option>{{ choice.choice_text }} <p class="text-xs">({{ choice.votes }} votes)</p></option>
            {% endfor %}
    </select> -->

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}Welcome | {% endblock %}

{% block content%}
    <!-- Polls  -->
    <p class="pt-6 pl-6 text-2xl font-semibold">Vote in any polls you like. Just click the Poll below</p>
    <div class="px-10 pt-4">
        {% if latest_question_list %}
        <ul class="list-disc flex flex-col gap-y-2">
            {% for question in latest_question_list %}
                <div class="flex gap-x-2">
                    <li class="font-semibold px-2 w-fit rounded-lg hover:bg-primary">
                        <a href={% url 'polls:detail' question.id %}>{{ question.question_text }}</a>
                    </li> 
                    <div class="tooltip tooltip-top tooltip-accent" data-tip="poll results">
                        <a href={% url 'polls:results' question.id %}>
                            <i class="fa-solid fa-square-poll-vertical text-accent hover:bg-primary rounded-lg"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </ul>
        {% else %}
            <p>No polls yet sir</p>
        {% endif %}
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="w-full p-6">
        {% if choices %}
        <p class="text-xl font-semibold mb-2">{{question}}</p>
        <ul class="flex flex-col gap-y-1 mb-4 ml-2">
            {% for choice in choices %}
                <li>{{ choice.choice_text }} -- <span class='font-semibold'>{{ choice.votes }} vote{{ choice.votes|pluralize }}</span></li>
                <progress class="progress progress-accent w-56" value="{{ choice.votes }}" max={{ total }}></progress>
            {% endfor %}
        </ul>

        <a class="btn btn-secondary ml-2" href={% url 'polls:detail' question.id %}>Vote again</a>
    {% else %}
        <p class="font-semibold">Question Does Not Exist</p>
        <a class='btn btn-secondary mt-4' href="{% url 'polls:index' %}">Back to Home</a>
    <div>
    {% endif %}
{% endblock %}